# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='antena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.PositiveIntegerField()),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complain_no', models.AutoField(primary_key=True, serialize=False)),
                ('csr_no', models.CharField(max_length=255)),
                ('item_qty', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invoice_price', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Invoice'),
        ),
        migrations.AddField(
            model_name='complain',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Invoice'),
        ),
        migrations.AddField(
            model_name='complain',
            name='item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Item'),
        ),
        migrations.AddField(
            model_name='complain',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddField(
            model_name='antena',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Invoice'),
        ),
        migrations.AddField(
            model_name='antena',
            name='item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Item'),
        ),
    ]
