# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190302_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecustomer',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Complain'),
        ),
        migrations.AlterField(
            model_name='employeecustomer',
            name='csr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customerservice'),
        ),
    ]
