# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190302_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='complainimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_path', models.CharField(max_length=255)),
                ('complain_no', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Complain')),
            ],
        ),
    ]
