# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_complainimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_path', models.CharField(max_length=255)),
                ('eawaybill_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='errornumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_no', models.PositiveIntegerField()),
                ('ter_no', models.PositiveIntegerField()),
                ('der_no', models.PositiveIntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='status',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='errornumbers',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Complain'),
        ),
        migrations.AddField(
            model_name='docs',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Complain'),
        ),
    ]
