# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190303_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='custemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
                ('csr_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.customerservice')),
            ],
        ),
    ]
