# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-02 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_custemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='recieved_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complain',
            name='returned_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
