# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190303_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_no',
            new_name='item_noo',
        ),
    ]
