# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190303_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='copy',
            fields=[
                ('item_noo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.PositiveIntegerField()),
            ],
        ),
    ]
