# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('row', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
