# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-03-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hoos',
            field=models.IntegerField(default=0),
        ),
    ]
