# Generated by Django 2.2.6 on 2019-10-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_track_hoos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainimages',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Complain'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Complain'),
        ),
        migrations.AlterField(
            model_name='employeecustomer',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Complain'),
        ),
        migrations.AlterField(
            model_name='employeecustomer',
            name='csr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.customerservice'),
        ),
        migrations.AlterField(
            model_name='errornumbers',
            name='complain_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Complain'),
        ),
    ]
